CREATE TABLE trilha(
	id SERIAL PRIMARY KEY,
	titulo VARCHAR(150),
	descricao TEXT,
	ativo BOOLEAN DEFAULT true,
	criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);