CREATE TABLE usuario(
	id SERIAL PRIMARY KEY,
	nome VARCHAR(150),
	email VARCHAR(150) UNIQUE,
	senha_hash VARCHAR(255),
	ativo BOOLEAN DEFAULT true,
	criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
